###
POST http://localhost:8089/api/getCompletedJobs
Content-Type: application/json

{
    "start":0,
    "end":0
}

###
POST http://localhost:8089/api/getJobs
Content-Type: application/json

{
    "state": "completed",
    "start":0,
    "end":1
}

###
POST http://localhost:8089/api/getSimulationJobs
Content-Type: application/json

{
    "end": 19,
    "start": 0,
    "simulationId": "52a06d23-4307-4150-bee6-d6900eacae06"
    

}

###
GET http://localhost:8089/api/getSimulationJobs?start=1
Content-Type: application/json

{
    "simulation": "2021-12-16T03.45.23.590Z",
    "type": "completed"
}

###
POST http://localhost:8089/api/getSimulations
Content-Type: application/json

{
    "simulation": "2021-12-16T03.45.23.590Z",
    "type": "completed"
}



###
POST http://localhost:8089/api/getSimulations
Content-Type: application/json

{
   "start": 0,
   "end:": 20
}

###
POST http://localhost:8089/api/getSimulationList
Content-Type: application/json

{
   "start": 0,
   "end:": 20
}